package com.iplanaylser;

public enum  SortingFields {
    AVERAGE, MAX_4s_AND_6s, MAX_4s_AND_6s_WITH_BEST_STRIKING_RATE, BEST_AVERAGE_WITH_STRIKE_RATE,
    MAX_RUNS_WITH_BEST_AVERAGE, BOWLING_STRIKING_RATES_WITH_MOST_4W_AND_5W, BOWLING_AVERAGE, STRIKING_RATE
}


