package com.iplanaylser;

public enum  SortingFields {
    BATTING_AVERAGE, MAX_4s_AND_6s, MAX_4s_AND_6s_WITH_BEST_STRIKING_RATE, BEST_AVERAGE_WITH_STRIKE_RATE,
    MAX_RUNS_WITH_BEST_AVERAGE, BOWLING_AVERAGE, TOP_BOWLING_STRIKING_RATES,
    TOP_BOWLING_ECONOMY_RATES, TOP_BOWLING_STRIKING_RATES_WITH_MOST_4Ws_AND_5Ws, GREAT_AVERAGE_WITH_BEST_STRIKING_RATE,
    BEST_BATTING_BOWLING_AVERAGE, ALL_ROUNDER, STRIKING_RATE
}


